config/routes.rb
FirstApp::Application.routes.draw do

  resources :users

  root :to => 'page#home'

  match '/contact', :to => 'page#contact'
  match '/home',     :to => 'page#home'
  match '/signup',   :to => 'users#new'
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates       :name, :presence => true,
                  :length => { :maximum => 50 }
  validates       :email, :presence => true,
                  :format => {:with => email_regex },
                  :uniqueness => { :case_sensitive => false}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
    @title = "Home"
  end

  def contact
    @title = "Contact"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @title = "Sign up"
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def title
		base_title = "Ruby on Rails Tutorial Sample App"
		if @title.nil?
			base_title
		else
			"#{base_title} | #{@title}"
	  end
  end
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class='round'>
    <ul>
      <li><%= link_to 'Contact', contact_path%></li>
      <li><a href="http://news.railstutorial.org">News</a></li>
      <li><a href="http://www.railstutorial.org">Rails Tutorial</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
    <%= logo = image_tag("logo.png", :alt => "Sample App", :class => "round") %>
    <%= link_to logo, root_path %>
    <nav class = "round">
        <ul>
            <li><%=link_to "Home", root_path %></li>
            <li><%=link_to "Sign in", "#" %></li>
        </ul>
    </nav>
 </header>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<%= stylesheet_link_tag 'custom',             :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
</head>
<body>
    <div class = 'container'>
        <%= render 'layouts/header' %>
        <section class = "round">
            <%= yield %>
        </section>
        <%= render 'layouts/footer' %>
        <%= debug(params) if Rails.env.development? %>
    </div>
</body>
</html>

app/views/page/contact.html.erb
<h1>Sample App - Contact</h1>

app/views/page/home.html.erb
<h1>Sample App - Home</h1>

<p>
  This is the home page for the RoR for Alex
</p>

<%= link_to "Sign up now!", signup_path, :class => "signup_button round" %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<%= @user.name %> , <%= @user.email %>